### ISSUE TITLE
Hopper w/ shooter

### ISSUE THREAD

**Issue by hell0w0rld2** [Raptacon/Robot-2022#101]
### Steps to Reproduce

1. Run auto shoot
2. Foreside hopper motor won't run

**Expected behavior:** Both motors run with the intake

**Actual behavior:** Only the backside motor runs

### Required Information

- What tag/branch/release of Robot code are you using?
  Branch: shooterHopperFix

### Useful Information

- What version of Python are you using? Which OS?

**Comment by ChrisHirsch** [comment]
Fixed in #94
