### ISSUE TITLE
Document Robot Code

### ISSUE THREAD

**Issue by Leaf-life** [Raptacon/Robot-2022#141]
### Description
Make document list and code map for robot code

**Is your feature request related to a problem? Please describe.**
Not having documentation of code, taking up time to have everyone figuring the code every time their is a edit.

**Describe the solution you'd like**
Document the code with comments, and making a document with doc strings so that we get an automatically updating list for the documentation of main. Create code map as well that outline how everything is working together and allowing easy navigation of the code, and double checking of the logic used (update on a regular bases, as new code is added)

**Describe alternatives you've considered**
I have not thought of any alternatives, if you have another idea that might fix this problem please tell.

**Additional context**
Needs to be easy to mange and for people to access since we have in the past sucked at it so the less work that has to be put in to maintain the documentation the better.

**Comment by ChrisHirsch** [comment]
Closing as won't do (2022)
