### ISSUE TITLE
Backup WIFI Solution

### ISSUE THREAD

**Issue by Leaf-life** [Raptacon/Robot-2022#145]
### Description
A Backup solution for WIFI

**Is your feature request related to a problem? Please describe.**
WIFI problems during computation.

**Describe the solution you'd like**
Another WIFI systems that can be switched to easy, Preferably in the middle of a match if possible.

**Describe alternatives you've considered**
Fancy ethernet cable.

**Additional context**
Happened a lot during our last comp. Because of issues with connectors and switch. Eventually determined it was something with the RoboRio.

**Comment by ChrisHirsch** [comment]
Won't do..not currently an issue
