### ISSUE TITLE
Tune shooter motors

### ISSUE THREAD

**Issue by ManiacMoustache** [Raptacon/Robot-2022#24]
Big thing - in order to shoot well, we need to come up with a set of optimal motor speeds for every distance. We could spin the ball!

- We don't have a shooter attached to a robot yet so we can't gather the data.

**Comment by ChrisHirsch** [comment]
Some takeaways from watching the first few matches at regionals today
- scoring cargo really is making all the difference in scores. Climb can make up for it but it's hit or miss.
-lots of bad turrets
-cargo ranking point is pretty easy to get if you have 2 robots scoring
-lots of penalties being called for robots hitting each other with robot parts outside frame perimeter, which is illegal this year.
You do not have time to sit and set up a shot. It has to be instant or you will get knocked around. Lots of back and forth traffic
Looks like when you nail your shot right in the center of the goal it bounces out a lot. But when you hit the inside edge of the goal it doesn't
Also auto scoring is making up a lot of the difference in points. Very low points scoring game
Image
You can have two robots climb and still get beat a lot by alliances that keep scoring cargo during the endgame time. As shown here
Discord thread: https://discord.com/channels/631631428764958750/631716560163176448/949384784101138432
