### ISSUE TITLE
Hopper

### ISSUE THREAD

**Issue by IanDKsemantic** [Raptacon/Robot-2022#60]
### Description

Modifying loading logic, shooter logic, and ball counter, that intakes how many balls are leaving and entering, moves balls to respective places in the hopper.

**Is your feature request related to a problem? Please describe.**
We have no code for the hopper, which gets the ball from loader to shooter

**Describe the solution you'd like**
Need the balls to move to appropriate loading locations in the hopper.

**Describe alternatives you've considered**
Maybe a component

**Additional context**
None at the moment

**Comment by hell0w0rld2** [comment]
The balls travel too far up the hopper so that they get stuck in the shooter wheels
