### ISSUE TITLE
Switch for tether

### ISSUE THREAD

**Issue by hell0w0rld2** [Raptacon/Robot-2022#79]
### Description

Need an ethernet switch on topside of robot for tethering on practice field

**Is your feature request related to a problem? Please describe.**
This will be necessary for us to use the practice field

**Describe the solution you'd like**
An ethernet switch needs to be mounted on the bot with possible ethernet connection

**Describe alternatives you've considered**
Running ethernet directly to brainpan, but that would require taking bellypan off and leaving wiring exposed

**Additional context**
[Add any other context or screenshots about the feature request here. REMOVE THIS WHEN DONE]

**Comment by ChrisHirsch** [comment]
Switch is now working and was installed in match 5
