### ISSUE TITLE
Auto Turret not working

### ISSUE THREAD

**Issue by ManiacMoustache** [Raptacon/Robot-2022#91]
### Description
When X is pressed on mechanism controller, turret doesn't move

### Steps to Reproduce

1. Press X on mechanism controller
2. If turret doesn't move, issue is present

**Expected behavior:**
Turret should scan and lock on limelight targets
**Actual behavior:**
Nothing
### Useful Information
This is on main

**Comment by ChrisHirsch** [comment]
Marked as done....there is another #98 that will ensure that turret works because it's calibrated

**Comment by ChrisHirsch** [comment]
Basically this happened because the turret wasn't calibrated or we were testing in an unknown branch
